services:
  termix:
    image: ghcr.io/lukegus/termix:latest
    container_name: termix
    restart: unless-stopped
    ports:
      - 8880:8080
    volumes:
      - ./appdata/termix:/app/data
    environment:
      PORT: "8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    environment:
      - DOZZLE_REMOTE_AGENT=192.168.0.13:7007
    ports:
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./appdata/homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
    ports:
      - 7575:7575
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3001:3000
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      HOMEPAGE_ALLOWED_HOSTS: "localhost:3000,127.0.0.1:3000,192.168.0.11:3333,localhost:3333,homepage.thehighestcommittee.com:443,homepage.thehighestcommittee.com:3333,homepage.thehighestcommittee.com"
      PUID: 0
      PGID: 0
      PORT: 3000
    ports:
      - 3333:3000
    volumes:
      - ./appdata/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro

    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
  newt:
    image: fosrl/newt:latest
    container_name: newt
    restart: unless-stopped
    environment:
      - PANGOLIN_ENDPOINT=https://pangolin.thehighestcommittee.com
      - NEWT_ID=yqdobjr1ihudyte
      - NEWT_SECRET=${NEWT_SECRET}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_FILE=none
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=${TZ}
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    ports:
      - 8191:8191
    volumes:
      - ./appdata/flaresolverr/config/:/config
    restart: unless-stopped
volumes:
  termix-data:
    driver: local
networks:
  default:
    name: shared
    external: true
